apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.postgres.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.containerPort }}