# Definimos el namespace común para todos los recursos
namespace: examen-alioune

# Variables de la Base de Datos
postgres:
  name: postgres-db
  image: aliounek/ubpostgres
  containerPort: 5432
  servicePort: 5432

# Variables de la API (NestJS)
api:
  name: nestjs-api
  image: aliounek/ubapi
  containerPort: 3001
  servicePort: 3001

# Variables del Frontend (NextJS)
frontend:
  name: nextjs-front
  image: aliounek/ubfrontend
  containerPort: 3000
  servicePort: 80 # Lo expondremos en el puerto 80 para el navegador