version: '3.8'

services:
  autocaravaneando:
    # Usamos la imagen final que acabas de construir
    image: alioune/ubautocaravaneando
    # El nombre del contenedor cogerá la variable del archivo .env
    container_name: ${CONTENEDOR}
    # Cargamos el archivo de variables
    env_file:
      - .env
    ports:
      - "${PORT_NODE}:3000"  # Desarrollo (React) -> 3010:3000
      - "${PORT_WWW}:80"     # Producción (Nginx) -> 8810:80
      - "${PORT_SSH}:22"     # Ciberseguridad (SSH) -> 45678:22
    # Para que el contenedor no se muera
    restart: always